FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["Kubernetes.TestService.Api/Kubernetes.TestService.Api.csproj", "Kubernetes.TestService.Api/"]
RUN dotnet restore "Kubernetes.TestService.Api/Kubernetes.TestService.Api.csproj"
COPY . .
WORKDIR "/src/Kubernetes.TestService.Api"
RUN dotnet build "Kubernetes.TestService.Api.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Kubernetes.TestService.Api.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Kubernetes.TestService.Api.dll"]